### ISSUE TITLE
Bug/Issue: Display information missing

### ISSUE THREAD

**Issue by DesertDog1178** [ChastiKey/chastikey.js#21]
**Describe the bug**
The display next to the name of people no longer works.

**To Reproduce**
Download the .js, do the api commands properly and get updated info but nothing shows when you click on people or when they type

**Expected behavior**
The display next to the name of people no longer works despite updating the chastikey information.

**Screenshots**

**Desktop (please complete the following information):**
BetterDiscord v1.0.0 (the complete redesign)

**Comment by rileyio** [comment]
Issue was reopened under rileyio/chastikeyinfo#7
