### ISSUE TITLE
Known Issue: Discard Pile missing/not populated from ListLocks & CheckLock on default requests

### ISSUE THREAD

**Issue by rileyio** [ChastiKey/chastikey.js#7]
Tracking - In discussion with @KevinCrossDCL as this needs to be addressed from the ChastiKey API side.

**Findings:**
on `/v0.4/listlocks.php`
  - **Has** Discard pile
  - **Has** Last Picked key & value
  - **Not available** `showdeleted = true` 

on `/v0.4/listlocks2.php` (**Default used in this wrapper**)
  - **No** Discard pile
  - **No** Last Picked key & value
  - **Available** `showdeleted = true` 

**Expected Behavior/Would fix:**
If I could fetch deleted locks, see their discard pile & also see the last picked timestamp all on `/v0.4/listlocks.php` I would just move the wrapper over to that.

**Additional Note(s):**
This may be moved out to a future API & Wrapper version, if it can be addressed under the current api version (at the time of tracking this `v0.4`) this will be corrected and an update to this wrapper released.

I'll review an optional way (time permitting) to add an override or possibly a condition based off `showdeleted` and its state (if set).

**Comment by rileyio** [comment]
Added `discardPile` and expected behavior to `ListLocksLock` object as of 65c009eb1ccc3d150722331df28846e5c321cb4d

**Comment by KevinCrossDCL** [comment]
As this is one that requires a change to the API I'm assigning myself. It looks similar to issue #8

**Comment by rileyio** [comment]
As the topic of this issue (discard pile in ListLocks) is superseded by the new `v0.5` LockeeData which contains the discard pile, I will be closing this issue.
