### ISSUE TITLE
Known Behavior: ListLocks requests with showdeleted only returns deleted or non-deleted, not both at once

### ISSUE THREAD

**Issue by rileyio** [ChastiKey/chastikey.js#8]
Tracking - In discussion with @KevinCrossDCL as this needs to be addressed from the ChastiKey API side to see if combining is possible to reduce needing to send 2 requests in certain use cases.

**Findings:**
on `/v0.4/listlocks.php`
  - **Not available** `showdeleted = true` 
  - Only shows deleted or non-deleted depending on `showdeleted` state, never both combined

on `/v0.4/listlocks2.php` (**Default used in this wrapper**)
  - **Available** `showdeleted = true` 
  - Only shows deleted or non-deleted depending on `showdeleted` state, never both combined

**Expected Behavior/Would fix:**
- Ideally:
  - `showdeleted` being available on `/v0.4/listlocks.php`
  - `showdeleted` being set to `true` would return both deleted and non-deleted locks

**Additional Note(s):**
This may be moved out to a future API & Wrapper version, if it can be addressed under the current api version (at the time of tracking this `v0.4`) this will be corrected and an update to this wrapper released.

I don't plan for the wrapper at this time to make 2 requests, if the end user of the wrapper requires both Deleted and Non-Deleted locks they can request & combine where needed - this is to keep from needless extra requests until a verdict is reached from Kevin's side.

**Comment by chastityai** [comment]
I would be interested in tackling this issue if it hasn't been assigned yet.

**Comment by KevinCrossDCL** [comment]
Same as #7 I will look at this one

**Comment by rileyio** [comment]
As ListLocks is superseded by the newer LockeeData request I will be closing this.
